name: A workflow for my Hello World file
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "deployingg"
      - run: echo "PRD_SECRET is $PRD_SECRET"
  my-job:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Michi"
      - run: echo "hoge"
      - name: LaunchDarkly Code References
        # You may pin to the exact commit or the version.
        # uses: launchdarkly/find-code-references@0ff20f7df8b53bfa155f2df9fd5877afaa2c1005
        uses: launchdarkly/find-code-references@v8
  print-date:
    runs-on: ubuntu-latest
    steps:
      - run: date -u
