name: A workflow for my Hello World file
on: push

jobs:
  my-job:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Michi"
      - run: echo "hoge"
  print-date:
    runs-on: ubuntu-latest
    steps:
      - run: date -u
